version: "3"
services:
    api:
        container_name: hallo-corona-be
        image: dharmatkj/hallo-corona-be:latest
        ports:
            - 5000:5000
        environment:
            - CHOKIDAR_USEPOLLING=true
            - NODE_ENV=production
